name: Push Audit
on: push

jobs:
  textformat:
    name: EditorConfig audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # 0: fetch all history for all tags/branches.
          # EditorConfig/Action needs all history in order to determine changed
          # files to support ALWAYS_LINT_ALL_FILES: false.
          fetch-depth: 0

      # Verify changed files conform to .editorconfig
      - name: EditorConfig-Action
        uses: zbeekman/EditorConfig-Action@master
        env:
          # Only lint files changed in the push.
          ALWAYS_LINT_ALL_FILES: false

          # Automatic error fixing not yet supported by EditorConfig-Action.
          # Forced off to avoid unintentionally enabling when upgrading to
          # new version.
          EC_FIX_ERROR: false

  ubuntu-build:
    name: Ubuntu Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.0.0
    - name: Build project
      uses: nicledomaS/cmake_build_action@v1.4
